change_in_place: true
excludes:
  - Cargo.lock
  - LICENSE
  - pgrx-sql-entity-graph/assets/ansi.tmTheme
  - ".envrc"
  - ".gitignore"
  - ".dockerignore"
  - "flake\\..*"
  - "logo.*"
  - ".github/**/*"
  - ".cargo/config.toml"
  - "cargo-pgrx/src/templates/*"
  - "cargo-pgrx/tests/fixtures/macos-universal-binary"
  - ".*\\.control"
  - ".*\\.md"
  - ".*\\.nix"
  - ".*\\.yml"
licenses:
  - files: any
    ident: MIT
    authors:
      - name: PgCentral Foundation, Inc.
        email: contact@pgcentral.org
    template: |
      Portions Copyright 2019-2021 ZomboDB, LLC.

      Portions Copyright 2021-2023 Technology Concepts & Design, Inc.

      Portions Copyright 2023-[year] [name of author]
      
      All rights reserved.
      
      Use of this source code is governed by the [ident] license that can be found in the LICENSE file.
comments:
  - columns: 120
    extensions:
      - rs
      - c
      - h
    commenter:
      type: line 
      comment_char: "//LICENSE"
      trailing_lines: 0
  - columns: 120
    extension: sql
    commenter:
      type: line
      comment_char: "--LICENSE"
      trailing_lines: 0
  - columns: 120
    extension: any
    commenter:
      type: line
      comment_char: "#LICENSE"
      trailing_lines: 0
    
